# Generated by Django 2.2 on 2019-05-15 19:06

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20190515_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.upload_image_path),
        ),
    ]
