# Generated by Django 2.2.2 on 2019-07-02 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0012_auto_20190702_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(default='', max_length=120)),
                ('phone', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='Enter your Products description', max_length=150)),
                ('image', models.ImageField(null=True, upload_to='documents/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
